baseURL = 'https://swananddhawan.github.io/'
languageCode = 'en-us'
title = "Swanand Dhawan | Tinkering thoughts"
theme = 'paper'
author = 'Swanand Dhawan'

enableGitInfo = true
googleAnalytics = "G-8FLQSX2479"
disqusShortname = "https-swananddhawan-github-io"

[frontmatter]
  date = ['date', 'publishDate', 'lastmod']
  expiryDate = ['expiryDate']
  lastmod = [':git', 'lastmod', 'date', 'publishDate']
  publishDate = ['publishDate', 'date']


[params]
  twitter = 'swananddhawan'
  github = 'swananddhawan'

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
